<?php


namespace App\Base;

use App\Common\Adapter\DAOAdapter;
use EasySwoole\Http\Message\Status;
use EasySwoole\Http\Request;
use EasySwoole\Http\Response;
use EasySwoole\Validate\Validate;

class BaseController extends ViewController
{
    protected $config;
    protected $session;
    public function __construct(string $actionName, Request $request, Response $response)
    {
        parent::__construct($actionName, $request, $response);
        $this->header();
    }

    public function index()
    {
        return false;
    }


    public function defineVariable()
    {


    }

    protected function onRequest($action): ?bool
    {
        return parent::onRequest($action); // TODO: Change the autogenerated stub
    }

    public function init($actionName, $request, $response)
    {
        $class_name                         = static::class;
        $array                              = explode('\\', $class_name);
        $GLOBALS['base']['MODULE_NAME']     = $array[2];
        $GLOBALS['base']['CONTROLLER_NAME'] = $array[3];
        $GLOBALS['base']['ACTION_NAME']     = $actionName;

        $_GET     = $request->getQueryParams();
        $_POST    = $request->getRequestParam();
        $_REQUEST = $request->getRequestParam();
        $_COOKIE  = $request->getCookieParams();

        $this->defineVariable();
        parent::init($actionName, $request, $response); // TODO: Change the autogenerated stub

        $_SESSION['user'] = $this->session()->get('user');
        $this->getView()->assign('session', $_SESSION['user']);
    }

    public function header()
    {
        $this->response()->withHeader('Content-type', 'text/html;charset=utf-8');
    }
    public function getParams(array $required, array $optional = [], DAOAdapter $adapter = null) :array
    {
        $param = [];
        $paramRules = $adapter ? $adapter->paramRules() : [];
        $validate = $this->getRules($required, $optional, $paramRules);
        if($this->validate($validate)) {
            $param = $validate->getVerifiedData();
        } else {
            $this->writeJson(Status::CODE_BAD_REQUEST, $validate->getError()->__toString(), 'fail');
        }
        return $param;
    }

    private function getRules(array $required, array $optional, array $paramRules)
    {
        $validate = new Validate();
        $paramNames = array_merge($required, $optional);
        foreach ($paramNames as $r) {
            $rule = $validate->addColumn($r);
            if(in_array($r, $required)) {
                $rule->required();
            }
            if(in_array($r, $optional)) {
                $rule->optional();
            }
            if (isset($paramRules[$r]) && is_array($paramRules[$r])) {
                foreach ($paramRules[$r] as $k => $v) {
                    switch ($k) {
                        case 'len':
                            $rule->lengthMax($v);
                            break;
                        case 'min':
                            $rule->min($v);
                            break;
                        case 'max':
                            $rule->max($v);
                            break;
                    }
                }
            }
        }
        return $validate;
    }

    public function inputResult($result = null, $code = Status::CODE_OK, $msg = 'success')
    {
        $this->writeJson($code, $result, $msg);
    }
}